### ISSUE TITLE
Create correct outputs from Falcon by changing the generation configuration

### ISSUE THREAD

**Issue by sebastian-weisshaar** [jina-ai/jerboa#103]
Falcon 7b and 40b generate outputs that are either cutoff in the middle or do not stop after the Eos token. We could solve this with the generation configuration. I will experiment with different settings to see if this resolves the issue.

**Comment by ThibaultDef** [comment]
I am facing the same problem. Did you finally find the best generation configuration for solving this ?
I have tried the most "logical" ones:
- temperature
- max_length
- num_return_sequences
But it seems it does't help that much
